CREATE TABLE products (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	price NUMERIC(10, 2) NOT NULL,
	code VARCHAR(50) NOT NULL,
    qtd NUMERIC(10, 2) NOT NULL,
	unity VARCHAR(50) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	UNIQUE (name, code)
);

CREATE TRIGGER set_updated_at
    BEFORE UPDATE
    ON public.products 
    FOR EACH ROW
EXECUTE PROCEDURE set_updated_at()
;