services:
  api_db:
    container_name: crud_product_api_db
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports: 
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}