services:
  api_app:
    container_name: crud_product_api_app
    restart: always
    build: .
    env_file:
      - app.env
    ports:
      - "3000:3000"
    depends_on:
      - api_db
  api_db:
    container_name: crud_product_api_db
    image: postgres:latest
    env_file:
      - db.env
    ports: 
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}