services:
  product_api_go_app:
    container_name: product_api_go_app
    restart: on-failure
    build: .
    env_file:
      - app.env
    ports:
      - "3000:3000"
    depends_on:
      - product_api_go_db
  product_api_go_db:
    container_name: product_api_go_db
    image: postgres:17.2-alpine3.21
    restart: on-failure
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  product_api_go_cache:
    container_name: product_api_go_cache
    image: redis:7.4.2-alpine3.21
    restart: always
    env_file:
      - cache.env
    ports:
      - "6379:6379"
    command: sh -c redis-server --requirepass $$REDIS_PASSWORD
    depends_on:
      - product_api_go_app
    volumes:
      - redisdata:/data

volumes:
  pgdata: {}
  redisdata: {}
