services:
  api_app:
    container_name: crud_product_api_app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - api_db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@api_db:5432/postgres
  api_db:
    container_name: crud_product_api_db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports: 
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}